---
- name: Create VPC Stack
  include: rol_vpc.yml
  when: create_vpc is defined and create_vpc
  tags:
    - create_vpc

- name: Create ASG stack
  include: rol_asg.yml
  when: create_asg is defined and create_asg
  tags:
    - create_asg is defined and create_asg
