---
- name: download packages
  get_url:
    url: '{{ item.url }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  with_items: '{{ packages }}'

- name: copy run.sh
  become: true
  become_user: root
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  with_items: '{{ appfiles }}'
  when: app_name == 'systems-engineer-interview'

- name: install dos2unix
  yum:
    name: dos2unix
    state: latest
  when: app_name == 'systems-engineer-interview'

- name: convert run.sh to dos2unix
  shell: dos2unix /app/bin/run.sh
  when: app_name == 'systems-engineer-interview'
