---

- hosts: localhost
  vars:
    stack_name: "{{ stack_name }}"
    state: "{{ state }}"
    email: "{{ email }}"
    keyname: "{{ keyname }}"
    imageid: "{{ imageid }}"
    instancetype: "{{ instancetype }}"
    alb_listener_port: 80
    alb_tg_port: 8080
    app_port: 8080
    vpc_stack: "{{ vpc_stack }}"
    vpccidr: "{{ vpccidr }}"

  roles:
    - role: cloudformation
      create_asg: True

#  tasks:
