---

- hosts: localhost
  vars:
    stack_name: "{{ stack_name }}"
    env: "{{ keyname }}"
    region: "{{ region }}"
    vpccidr: "{{ vpccidr }}"
    pub_sub_1: "{{ pub_sub_1 }}"
    pub_sub_2: "{{ pub_sub_2 }}"
    priv_sub_1: "{{ priv_sub_1 }}"
    priv_sub_2: "{{ priv_sub_2 }}"
    state: "{{ state }}"

  roles:
    - role: cloudformation
      create_vpc: True

#  tasks:
